on:
  push:
    branches:
      - master

jobs:
  migrate-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        name: Checkout Repository

      - name: Install Golang Migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          which migrate

      - name: Running Migrate DB
        run: make db_up DB_URL="${{secrets.PROD_POSTGRES_URL}}"

  deploy-job:
    needs:
      - migrate-db
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: ${{ github.event.repository.name }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v4.2.2
        name: Checkout Repository

      - name: Deploy to Railway
        run: |
          railway up -s $SVC_ID \
            -i ${{ secrets.DOCKERHUB_USERNAME }}/${{secrets.IMAGE_NAME}}:${{secrets.IMAGE_TAG}} \
            -e PORT=${{ secrets.PORT }} \
            -e CACHE_DB_NAME=${{ secrets.REDIS_NAME }} \
            -e CACHE_DB_HOST=${{ secrets.PROD_REDIS_HOST }} \
            -e CACHE_DB_PORT=${{ secrets.PROD_REDIS_PORT }} \
            -e CACHE_DB_USER=${{ secrets.PROD_REDIS_USER }} \
            -e CACHE_DB_PASS=${{ secrets.PROD_REDIS_PASSWORD }} \
            -e CACHE_DB_MAX_CON=${{ secrets.REDIS_MAX_CON }} \
            -e CACHE_DB_MIN_CON=${{ secrets.REDIS_MIN_CON }} \
            -e CACHE_DB_MAX_TIME=${{ secrets.REDIS_MAX_TIME }} \
            -e CACHE_DB_MIN_TIME=${{ secrets.REDIS_MIN_TIME }} \
            -e MODEL_PATH=${{ secrets.MODEL_PATH }} \
            -e FIBER_HOST=${{ secrets.FIBER_HOST }} \
            -e FIBER_PORT=${{ secrets.FIBER_PORT }} \
            -e FIBER_PREFORK=${{ secrets.FIBER_PREFORK }} \
            -e FIBER_STRICT_ROUTING=${{ secrets.FIBER_STRICT_ROUTING }} \
            -e FIBER_CASE_SENSITIVE=${{ secrets.FIBER_CASE_SENSITIVE }} \
            -e FIBER_BODY_LIMIT=${{ secrets.FIBER_BODY_LIMIT }} \
            -e FIBER_READ_TIMEOUT=${{ secrets.FIBER_READ_TIMEOUT }} \
            -e FIBER_WRITE_TIMEOUT=${{ secrets.FIBER_WRITE_TIMEOUT }} \
            -e FIBER_REDUCE_MEMU=${{ secrets.FIBER_REDUCE_MEMU }} \
            -e FIBER_JSON=${{ secrets.FIBER_JSON }} \
            -e HASH_SALT=${{ secrets.PROD_HASH_SALT }} \
            -e LOG_PATH=${{ secrets.LOG_PATH }} \
            -e LOG_MAX_SIZE=${{ secrets.LOG_MAX_SIZE }} \
            -e LOG_MAX_BACKUP=${{ secrets.LOG_MAX_BACKUP }} \
            -e LOG_MAX_SIZE_ROTATE=${{ secrets.LOG_MAX_SIZE_ROTATE }} \
            -e LOG_TIME_FORMAT=${{ secrets.LOG_TIME_FORMAT }} \
            -e LOG_COLOR_OUTPUT=${{ secrets.LOG_COLOR_OUTPUT }} \
            -e LOG_QUOTE_STR=${{ secrets.LOG_QUOTE_STR }} \
            -e LOG_END_WITH_MESSAGE=${{ secrets.LOG_END_WITH_MESSAGE }} \
            -e DB_DRIVER=${{ secrets.POSTGRES_DRIVER }} \
            -e DB_PROTOCOL=${{ secrets.POSTGRES_PROTOCOL }} \
            -e DB_NAME=${{ secrets.PROD_POSTGRES_DB }} \
            -e DB_HOST=${{ secrets.PROD_POSTGRES_HOST }} \
            -e DB_PORT=${{ secrets.PROD_POSTGRES_PORT }} \
            -e DB_USER=${{ secrets.PROD_POSTGRES_USER }} \
            -e DB_PASS=${{ secrets.PROD_POSTGRES_PASSWORD }} \
            -e DB_MAX_CON=${{ secrets.POSTGRES_MAX_CON }} \
            -e DB_MIN_CON=${{ secrets.POSTGRES_MIN_CON }} \
            -e DB_MAX_TIME=${{ secrets.POSTGRES_MAX_TIME }} \
            -e DB_MIN_TIME=${{ secrets.POSTGRES_MIN_TIME }} \
            -e TOKEN_NAME=${{ secrets.PROD_TOKEN_NAME }} \
            -e SECRET_KEY_ACCESS_TOKEN=${{ secrets.PROD_SECRET_KEY_ACCESS_TOKEN }} \
            -e SECRET_KEY_REFRESH_TOKEN=${{ secrets.PROD_SECRET_KEY_REFRESH_TOKEN }} \
            -e SECRET_KEY_FP_TOKEN=${{ secrets.PROD_SECRET_KEY_FP_TOKEN }} \ 
            -e SECRET_KEY_CSRF=${{ secrets.PROD_SECRET_KEY_CSRF }} \
            -e SECRET_TEST_CLIENT=${{ secrets.PROD_SECRET_TEST_CLIENT }} \ 
            -e CACHE_TIMEOUT=${{ secrets.REDIS_TIMEOUT }} \
            -e DB_TIMEOUT=${{ secrets.POSTGRES_TIMEOUT }} \
            -e DOWN_STREAM_TIMEOUT=${{ secrets.DOWN_STREAM_TIMEOUT }} \
            -e CORS_ALLOW_METHODS=${{ secrets.CORS_ALLOW_METHODS }} \
            -e CORS_ALLOW_HEADERS=${{ secrets.CORS_ALLOW_HEADERS }} \
            -e CORS_EXPOSE_HEADERS=${{ secrets.CORS_EXPOSE_HEADERS }} \
            -e CORS_ALLOW_ORIGINS=${{ secrets.PROD_CORS_ALLOW_ORIGINS }} \ 
            -e CORS_ALLOW_CREDENTIALS=${{ secrets.CORS_ALLOW_CREDENTIALS }}